# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b8627ce77b48fe3870bcffb3732a1a4456fb20cd8c14051e67afb05c9a4433db592f1ac4ee4b1c7023f854d042a3d7bcb60e8f339a8ee372f3230ee60b9c24

test:
  secret_key_base: 3ecaa79c56f75ec29aef5d1f47330c61c643d95d54c50f9338749fd7d3a8ff868f0445b8d591164e4c1b683857e7c02d1bda7042326f5e8253c2d1d614033024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
